# Config file dedicated to the user's personal zshrc profile shared between all exegol containers.
# This file is sourced in /root/.zshrc file.
# Alternatively, the /opt/my-resources/setup/load_user_setup.sh file can be used to operate the change once (instead of sourcing a file for each zsh instance)

# Overwrite here is necessary
# Setup completion
autoload -Uz compinit && compinit

# Share command history between tmux panes
setopt incappendhistory
setopt sharehistory

alias ll="exa -lag --group-directories-first"
# alias ll='exa -la --group-directories-first --no-user --no-filesize --no-time --no-permissions'
export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=gasp'

touch /workspace/.env && source /workspace/.env
# WORKDIR=/workspace
# TARGETS=/workspace/targets
# ATTACKS=/workspace/attacks
# LOOT=/workspace/loot
# DIR_TARGETS=/workspace/targets
# DIR_LOOT=/workspace/loot
# DIR_ATTACKS=/workspace/attacks
# DC_HOST=$DC

# Go installation
ln -sf /root/.asdf/installs/golang/1.22.2/packages ~/go
export PATH="$HOME/go/bin:$PATH"