# Config file dedicated to the user's personal zshrc profile shared between all exegol containers.
# This file is sourced in /root/.zshrc file.
# Alternatively, the /opt/my-resources/setup/load_user_setup.sh file can be used to operate the change once (instead of sourcing a file for each zsh instance)

# Overwrite here is necessary
# Setup completion
autoload -Uz compinit && compinit

# Share command history between tmux panes
setopt incappendhistory
setopt sharehistory

# Overwrite exegol ones
alias ll='ls -lF --group-directories-first'
alias la='ls -A --group-directories-first'
alias l='ls -CF --group-directories-first'

# Wiki read file
alias wkread='f() { cd /opt/my-resources/wiki && bat -p -l md "$(find . -type f -name "*.md" | fzf)" }; f'
# Wiki write / edit file
alias wkedit='f() { cd /opt/my-resources/wiki && subl "$(find . -type f -name "*.md" | fzf)" }; f'
# Wiki open
alias wkopen='subl /opt/my-resources/wiki'